:concurrency: 5
:queues:
  - [default, 1]
  - [mailers, 2]
  - [critical, 3]

:max_retries: 3
:retry_interval: 5

# Redis configuration
:redis:
  :url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  :namespace: search_analytics_<%= Rails.env %>
